name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Rust Toolchain Nightly
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Format
        run: cargo +nightly fmt --check --all

  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install libraries
      run: |
        sudo apt update
        sudo apt install -y librust-alsa-sys-dev libudev-dev
    - name: Rust Toolchain Clippy
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
    - name: Clippy
      run: cargo clippy --no-deps

  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Install libraries
      run: |
        sudo apt update
        sudo apt install -y librust-alsa-sys-dev libudev-dev
    - name: Rust Toolchain Default
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build Tests
      run: cargo test --workspace --no-run
    - name: Run Tests
      run: cargo test --workspace
